name: CD - QA

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/example-app

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Env test
        run: echo ${{ env.IMAGE_NAME }}